#!/bin/bash

WALLPAPERS_DIR="$HOME/Pictures/wallpapers"

DEFAULT_WALLPAPER="$WALLPAPERS_DIR/default/wall"

# pick a wallpaper with rofi
chosen=$(ls $WALLPAPERS_DIR | grep -v "default" | rofi -dmenu -i)

# copy chosen wallpaper to the default wallpaper directory and rename it to wall
cp "$WALLPAPERS_DIR/$chosen" "$DEFAULT_WALLPAPER"

# select default wallpaper as current one with swww
swww img --transition-type center "$DEFAULT_WALLPAPER"
